name: Firebase App Distribution

on:
  push:
    tags:
      - 'v*'

env:
  SECRET_KEY: ${{ secrets.SECRET_KEY }}
  BASE_URL: ${{ secrets.BASE_URL }}
  API_KEY: ${{ secrets.API_KEY }}
  NETWORK_LOGGER: false

jobs:
  validate-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Validate version format
        run: |
          if [[ ! ${{ github.ref_name }} =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Error: Tag must follow semantic versioning format (vX.Y.Z)"
            exit 1
          fi

  build-android:
    needs: validate-version
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          channel: 'stable'
      
      - name: Create .env file
        run: |
          echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" > .env
          echo "BASE_URL=${{ secrets.BASE_URL }}" >> .env
          echo "API_KEY=${{ secrets.API_KEY }}" >> .env
          echo "NETWORK_LOGGER=false" >> .env
      
      - name: Install dependencies
        run: flutter pub get
      
      - name: Generate release notes
        id: release_notes
        run: |
          git fetch --prune --unshallow || true
          COMMITS=$(git log --pretty=format:"- %s" -n 5)
          echo "RELEASE_NOTES<<EOF" >> $GITHUB_ENV
          echo "Release ${{ github.ref_name }}" >> $GITHUB_ENV
          echo "" >> $GITHUB_ENV
          echo "Recent changes:" >> $GITHUB_ENV
          echo "$COMMITS" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
      
      - name: Build Android APK
        run: |
          cd android
          ./gradlew clean
          cd ..
          flutter build apk --debug
          if [ $? -ne 0 ]; then
            echo "Build failed, showing stacktrace..."
            cd android
            ./gradlew assembleDebug --stacktrace --info
            exit 1
          fi
      
      - name: Upload Android APK
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: build/app/outputs/flutter-apk/app-debug.apk
      
      - name: Firebase App Distribution - Android
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_ANDROID_APP_ID }}
          groups: qa-testers
          file: build/app/outputs/flutter-apk/app-debug.apk
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          releaseNotes: ${{ env.RELEASE_NOTES }}

  build-ios:
    needs: validate-version
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          channel: 'stable'
      
      - name: Create .env file
        run: |
          echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" > .env
          echo "BASE_URL=${{ secrets.BASE_URL }}" >> .env
          echo "API_KEY=${{ secrets.API_KEY }}" >> .env
          echo "NETWORK_LOGGER=false" >> .env
      
      - name: Install dependencies
        run: flutter pub get
      
      - name: Generate release notes
        id: release_notes
        run: |
          git fetch --prune --unshallow || true
          COMMITS=$(git log --pretty=format:"- %s" -n 5)
          echo "RELEASE_NOTES<<EOF" >> $GITHUB_ENV
          echo "Release ${{ github.ref_name }}" >> $GITHUB_ENV
          echo "" >> $GITHUB_ENV
          echo "Recent changes:" >> $GITHUB_ENV
          echo "$COMMITS" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
      
      - name: Setup iOS build environment
        run: |
          cd ios
          pod repo update
          pod install --repo-update
          cd ..
      
      - name: Build iOS IPA
        run: |
          flutter build ipa --debug --no-codesign
          if [ $? -ne 0 ]; then
            echo "Build failed, showing stacktrace..."
            cd ios
            xcodebuild -workspace Runner.xcworkspace -scheme Runner -configuration Debug -sdk iphoneos -verbose
            exit 1
          fi
      
      - name: Upload iOS IPA
        uses: actions/upload-artifact@v4
        with:
          name: debug-ipa
          path: build/ios/ipa/Runner.ipa
      
      - name: Firebase App Distribution - iOS
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_IOS_APP_ID }}
          groups: qa-testers
          file: build/ios/ipa/Runner.ipa
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          releaseNotes: ${{ env.RELEASE_NOTES }} 